"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from decouple import config
# import pymongo
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oo4e4r#x+wfy*nh--(r(9ep0*qmkey4jhnm4t^gc%71=0djzvi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # ... Django internal apps
    'rest_framework',
    'rest_framework_simplejwt',
    # 'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_spectacular',
    'corsheaders',
    
    # Flat application domain paths
    'core',
    'users',
    'inventory',
    'auditing',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Top par hona chahiye CommonMiddleware ke
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.GlobalUserRequestContextMiddleware',  # Auth middleware ke BAAD rakhein
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    # MySQL engine is active by default as per your primary selection.
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='inventory_mysql_db'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='127.0.0.1'),
        'PORT': config('DB_PORT', default=3306, cast=int),
        'ATOMIC_REQUESTS': True,  # Ensures rollback on intercepted exception loops
        'OPTIONS': {
            # 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'init_command': (
                "SET SESSION innodb_strict_mode=OFF;"
            ),
            'charset': 'utf8mb4',
        },
    },
    # PostgreSQL Configuration Block (Backup/Alternative Setup)
    # 'postgresql_alternative': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': config('PG_DB_NAME', default='inventory_pg_db'),
    #     'USER': config('PG_DB_USER', default='postgres'),
    #     'PASSWORD': config('PG_DB_PASSWORD', default='postgres'),
    #     'HOST': config('PG_DB_HOST', default='127.0.0.1'),
    #     'PORT': config('PG_DB_PORT', default=5432, cast=int),
    #     'ATOMIC_REQUESTS': True,
    # },
    
    # # SQL Server (MSSQL) Configuration Block
    # 'sql_server_alternative': {
    #     'ENGINE': 'mssql',
    #     'NAME': config('SQL_SERVER_DB', default='inventory_ms_db'),
    #     'USER': config('SQL_SERVER_USER', default='sa'),
    #     'PASSWORD': config('SQL_SERVER_PASSWORD', default='HighlySecurePassword123'),
    #     'HOST': config('SQL_SERVER_HOST', default='127.0.0.1'),
    #     'PORT': config('SQL_SERVER_PORT', default=1433, cast=int),
    #     'OPTIONS': {
    #         'driver': 'ODBC Driver 17 for SQL Server',
    #     },
    # }
}
# MONGO_URI = config('MONGO_URI', default='mongodb://localhost:27017/')
# MONGO_CLIENT = pymongo.MongoClient(MONGO_URI)
# MONGO_DB = MONGO_CLIENT[config('MONGO_DB_NAME', default='inventory_nosql_logs')]


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





#Custom Configuration

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Core application baseline authentication map
]

# Enforces Django engine to bypass standard auth.User and bind identity structures to CustomUser
AUTH_USER_MODEL = 'users.CustomUser'
# React Dev aur Production boundaries map karein
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:5173,http://127.0.0.1:5173').split(',')
CORS_ALLOW_CREDENTIALS = True

# DRF Pipeline Extensions Setup
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Swagger Metadata & Structural Customization
SPECTACULAR_SETTINGS = {
    'TITLE': 'Distributed Inventory & Lock Engine API Core Matrix',
    'DESCRIPTION': 'Production level real-time allocation and locking pipeline architecture documentation.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SECURITY': [
        {
            'BearerAuth': [],
        }
    ],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'Authorization',
                'description': 'Token configuration payload structure format: Bearer <JWT_ACCESS_TOKEN>'
            }
        }
    }
}

LOGS_DIR = os.path.join(BASE_DIR, 'storage/logs')
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json_standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s.%(funcName)s:%(lineno)d - %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json_standard',
        },
        'system_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'system_errors.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB per file maximum footprint
            'backupCount': 5,
            'formatter': 'json_standard',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'system_file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}