# Generated by Django 5.1.15 on 2026-05-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTransactionLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_url', models.URLField(max_length=500)),
                ('http_method', models.CharField(max_length=10)),
                ('provider_name', models.CharField(db_index=True, max_length=100)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout')], max_length=20)),
                ('execution_time_ms', models.FloatField(help_text='Duration spent fulfilling the pipeline loop.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_data_transactions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserTransactionLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(db_index=True, max_length=100)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOCK_ACQUIRED', 'Lock Acquired')], max_length=20)),
                ('old_state', models.JSONField(blank=True, help_text='State footprint before transformation.', null=True)),
                ('new_state', models.JSONField(blank=True, help_text='State footprint after transformation.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_user_transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
